# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bj/文档/scout4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bj/文档/scout4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bj/文档/scout4/CMakeFiles /home/bj/文档/scout4/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bj/文档/scout4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named scout

# Build rule for target.
scout: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scout
.PHONY : scout

# fast build rule for target.
scout/fast:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/build
.PHONY : scout/fast

src/crc16.o: src/crc16.cpp.o
.PHONY : src/crc16.o

# target to build an object file
src/crc16.cpp.o:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/crc16.cpp.o
.PHONY : src/crc16.cpp.o

src/crc16.i: src/crc16.cpp.i
.PHONY : src/crc16.i

# target to preprocess a source file
src/crc16.cpp.i:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/crc16.cpp.i
.PHONY : src/crc16.cpp.i

src/crc16.s: src/crc16.cpp.s
.PHONY : src/crc16.s

# target to generate assembly for a file
src/crc16.cpp.s:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/crc16.cpp.s
.PHONY : src/crc16.cpp.s

src/crc32.o: src/crc32.cpp.o
.PHONY : src/crc32.o

# target to build an object file
src/crc32.cpp.o:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/crc32.cpp.o
.PHONY : src/crc32.cpp.o

src/crc32.i: src/crc32.cpp.i
.PHONY : src/crc32.i

# target to preprocess a source file
src/crc32.cpp.i:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/crc32.cpp.i
.PHONY : src/crc32.cpp.i

src/crc32.s: src/crc32.cpp.s
.PHONY : src/crc32.s

# target to generate assembly for a file
src/crc32.cpp.s:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/crc32.cpp.s
.PHONY : src/crc32.cpp.s

src/fhog.o: src/fhog.cpp.o
.PHONY : src/fhog.o

# target to build an object file
src/fhog.cpp.o:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/fhog.cpp.o
.PHONY : src/fhog.cpp.o

src/fhog.i: src/fhog.cpp.i
.PHONY : src/fhog.i

# target to preprocess a source file
src/fhog.cpp.i:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/fhog.cpp.i
.PHONY : src/fhog.cpp.i

src/fhog.s: src/fhog.cpp.s
.PHONY : src/fhog.s

# target to generate assembly for a file
src/fhog.cpp.s:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/fhog.cpp.s
.PHONY : src/fhog.cpp.s

src/hogdetector.o: src/hogdetector.cpp.o
.PHONY : src/hogdetector.o

# target to build an object file
src/hogdetector.cpp.o:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/hogdetector.cpp.o
.PHONY : src/hogdetector.cpp.o

src/hogdetector.i: src/hogdetector.cpp.i
.PHONY : src/hogdetector.i

# target to preprocess a source file
src/hogdetector.cpp.i:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/hogdetector.cpp.i
.PHONY : src/hogdetector.cpp.i

src/hogdetector.s: src/hogdetector.cpp.s
.PHONY : src/hogdetector.s

# target to generate assembly for a file
src/hogdetector.cpp.s:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/hogdetector.cpp.s
.PHONY : src/hogdetector.cpp.s

src/kcftracker.o: src/kcftracker.cpp.o
.PHONY : src/kcftracker.o

# target to build an object file
src/kcftracker.cpp.o:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/kcftracker.cpp.o
.PHONY : src/kcftracker.cpp.o

src/kcftracker.i: src/kcftracker.cpp.i
.PHONY : src/kcftracker.i

# target to preprocess a source file
src/kcftracker.cpp.i:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/kcftracker.cpp.i
.PHONY : src/kcftracker.cpp.i

src/kcftracker.s: src/kcftracker.cpp.s
.PHONY : src/kcftracker.s

# target to generate assembly for a file
src/kcftracker.cpp.s:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/kcftracker.cpp.s
.PHONY : src/kcftracker.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/myevent.o: src/myevent.cpp.o
.PHONY : src/myevent.o

# target to build an object file
src/myevent.cpp.o:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/myevent.cpp.o
.PHONY : src/myevent.cpp.o

src/myevent.i: src/myevent.cpp.i
.PHONY : src/myevent.i

# target to preprocess a source file
src/myevent.cpp.i:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/myevent.cpp.i
.PHONY : src/myevent.cpp.i

src/myevent.s: src/myevent.cpp.s
.PHONY : src/myevent.s

# target to generate assembly for a file
src/myevent.cpp.s:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/myevent.cpp.s
.PHONY : src/myevent.cpp.s

src/mylock.o: src/mylock.cpp.o
.PHONY : src/mylock.o

# target to build an object file
src/mylock.cpp.o:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/mylock.cpp.o
.PHONY : src/mylock.cpp.o

src/mylock.i: src/mylock.cpp.i
.PHONY : src/mylock.i

# target to preprocess a source file
src/mylock.cpp.i:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/mylock.cpp.i
.PHONY : src/mylock.cpp.i

src/mylock.s: src/mylock.cpp.s
.PHONY : src/mylock.s

# target to generate assembly for a file
src/mylock.cpp.s:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/mylock.cpp.s
.PHONY : src/mylock.cpp.s

src/mythread.o: src/mythread.cpp.o
.PHONY : src/mythread.o

# target to build an object file
src/mythread.cpp.o:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/mythread.cpp.o
.PHONY : src/mythread.cpp.o

src/mythread.i: src/mythread.cpp.i
.PHONY : src/mythread.i

# target to preprocess a source file
src/mythread.cpp.i:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/mythread.cpp.i
.PHONY : src/mythread.cpp.i

src/mythread.s: src/mythread.cpp.s
.PHONY : src/mythread.s

# target to generate assembly for a file
src/mythread.cpp.s:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/mythread.cpp.s
.PHONY : src/mythread.cpp.s

src/mytim.o: src/mytim.cpp.o
.PHONY : src/mytim.o

# target to build an object file
src/mytim.cpp.o:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/mytim.cpp.o
.PHONY : src/mytim.cpp.o

src/mytim.i: src/mytim.cpp.i
.PHONY : src/mytim.i

# target to preprocess a source file
src/mytim.cpp.i:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/mytim.cpp.i
.PHONY : src/mytim.cpp.i

src/mytim.s: src/mytim.cpp.s
.PHONY : src/mytim.s

# target to generate assembly for a file
src/mytim.cpp.s:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/mytim.cpp.s
.PHONY : src/mytim.cpp.s

src/ramp.o: src/ramp.cpp.o
.PHONY : src/ramp.o

# target to build an object file
src/ramp.cpp.o:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/ramp.cpp.o
.PHONY : src/ramp.cpp.o

src/ramp.i: src/ramp.cpp.i
.PHONY : src/ramp.i

# target to preprocess a source file
src/ramp.cpp.i:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/ramp.cpp.i
.PHONY : src/ramp.cpp.i

src/ramp.s: src/ramp.cpp.s
.PHONY : src/ramp.s

# target to generate assembly for a file
src/ramp.cpp.s:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/ramp.cpp.s
.PHONY : src/ramp.cpp.s

src/serial.o: src/serial.cpp.o
.PHONY : src/serial.o

# target to build an object file
src/serial.cpp.o:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/serial.cpp.o
.PHONY : src/serial.cpp.o

src/serial.i: src/serial.cpp.i
.PHONY : src/serial.i

# target to preprocess a source file
src/serial.cpp.i:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/serial.cpp.i
.PHONY : src/serial.cpp.i

src/serial.s: src/serial.cpp.s
.PHONY : src/serial.s

# target to generate assembly for a file
src/serial.cpp.s:
	$(MAKE) -f CMakeFiles/scout.dir/build.make CMakeFiles/scout.dir/src/serial.cpp.s
.PHONY : src/serial.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... scout"
	@echo "... src/crc16.o"
	@echo "... src/crc16.i"
	@echo "... src/crc16.s"
	@echo "... src/crc32.o"
	@echo "... src/crc32.i"
	@echo "... src/crc32.s"
	@echo "... src/fhog.o"
	@echo "... src/fhog.i"
	@echo "... src/fhog.s"
	@echo "... src/hogdetector.o"
	@echo "... src/hogdetector.i"
	@echo "... src/hogdetector.s"
	@echo "... src/kcftracker.o"
	@echo "... src/kcftracker.i"
	@echo "... src/kcftracker.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/myevent.o"
	@echo "... src/myevent.i"
	@echo "... src/myevent.s"
	@echo "... src/mylock.o"
	@echo "... src/mylock.i"
	@echo "... src/mylock.s"
	@echo "... src/mythread.o"
	@echo "... src/mythread.i"
	@echo "... src/mythread.s"
	@echo "... src/mytim.o"
	@echo "... src/mytim.i"
	@echo "... src/mytim.s"
	@echo "... src/ramp.o"
	@echo "... src/ramp.i"
	@echo "... src/ramp.s"
	@echo "... src/serial.o"
	@echo "... src/serial.i"
	@echo "... src/serial.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

